clusterName: k8s.clt.johnson.computer
talosVersion: v1.3.5
kubernetesVersion: v1.25.7
endpoint: https://api.k8s.clt.johnson.computer:6443
domain: cluster.local
allowSchedulingOnMasters: true

additionalMachineCertSans:
  - api.k8s.clt.johnson.computer
  - 10.0.2.5

additionalApiServerCertSans:
  - api.k8s.clt.johnson.computer
  - 10.0.2.5

clusterPodNets:
  - 10.244.0.0/16

clusterSvcNets:
  - 10.96.0.0/12

cniConfig:
  name: custom
  urls:
    - https://s3.us-east-1.amazonaws.com/uploads2.johnson.software/cilium.yaml

nodes:
  - hostname: hv01.clt.johnson.computer
    ipAddress: 10.0.2.10
    installDisk: /dev/nvme0n1
    controlPlane: true
    nodeLabels:
      kubernetes.io/hostname: hv01.clt.johnson.computer
      topology.kubernetes.io/region: us-east-1
      topology.kubernetes.io/zone: us-east-1a
      node.kubernetes.io/instance-type: t330-gen1
    nameservers:
      - 1.0.0.1
      - 1.1.1.1
    networkInterfaces:
      - interface: eth2
        addresses:
          - 10.0.2.10/24
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.2.1
        vip: &control_node_vip
          ip: 10.0.2.5
        # wireguard:
        #   privateKey: 6NtibgkNWGSLp7ud6NgZr9k3kNhlQiaJCVW6vN+j9UY=
        #   listenPort: 51111
        #   peers:
        #     - publicKey: kyiu4YOZqX+7tY4fdiIRNDe2lSEvlun76EWtD/jP1hU=
        #       endpoint: 192.168.1.3:1111
        #       allowedIPs:
        #         - 192.168.1.0/24
        #       persistentKeepaliveInterval: 10s
      # eno1
      - interface: eth0
        dhcp: false
        ignore: true
      # eno2
      - interface: eth1
        dhcp: false
        ignore: true
  - hostname: hv02.clt.johnson.computer
    ipAddress: 10.0.2.10
    installDisk: /dev/nvme0n1
    controlPlane: false
    nodeLabels:
      kubernetes.io/hostname: hv02.clt.johnson.computer
      topology.kubernetes.io/region: us-east-1
      topology.kubernetes.io/zone: us-east-1a
      node.kubernetes.io/instance-type: r430-gen1
    nameservers:
      - 1.0.0.1
      - 1.1.1.1
    patches:
      - "@./patches/enable-sr-iov.yaml"
    networkInterfaces:
      - interface: eth4
        addresses:
          - 10.0.2.11/24
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.2.1
        # wireguard:
        #   privateKey: 6NtibgkNWGSLp7ud6NgZr9k3kNhlQiaJCVW6vN+j9UY=
        #   listenPort: 51111
        #   peers:
        #     - publicKey: kyiu4YOZqX+7tY4fdiIRNDe2lSEvlun76EWtD/jP1hU=
        #       endpoint: 192.168.1.3:1111
        #       allowedIPs:
        #         - 192.168.1.0/24
        #       persistentKeepaliveInterval: 10s
      # eno1
      - interface: eth0
        dhcp: false
        ignore: true
      # eno2
      - interface: eth1
        dhcp: false
        ignore: true
      # eno3
      - interface: eth2
        dhcp: false
        ignore: true
      # eno4
      - interface: eth3
        dhcp: false
        ignore: true
  - hostname: hv04.clt.johnson.computer
    ipAddress: 10.0.2.13
    installDisk: /dev/nvme0n1
    controlPlane: true
    nodeLabels:
      kubernetes.io/hostname: hv04.clt.johnson.computer
      topology.kubernetes.io/region: us-east-1
      topology.kubernetes.io/zone: us-east-1a
      node.kubernetes.io/instance-type: r430-gen2-r1
    nameservers:
      - 1.0.0.1
      - 1.1.1.1
    networkInterfaces:
      - interface: eth4
        addresses:
          - 10.0.2.13/24
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.2.1
        vip: *control_node_vip
        # wireguard:
        #   privateKey: 6NtibgkNWGSLp7ud6NgZr9k3kNhlQiaJCVW6vN+j9UY=
        #   listenPort: 51111
        #   peers:
        #     - publicKey: kyiu4YOZqX+7tY4fdiIRNDe2lSEvlun76EWtD/jP1hU=
        #       endpoint: 192.168.1.3:1111
        #       allowedIPs:
        #         - 192.168.1.0/24
        #       persistentKeepaliveInterval: 10s
      # eno1
      - interface: eth0
        dhcp: false
        ignore: true
      # eno2
      - interface: eth1
        dhcp: false
        ignore: true
      # eno3
      - interface: eth2
        dhcp: false
        ignore: true
      # eno4
      - interface: eth3
        dhcp: false
        ignore: true
  - hostname: hv05.clt.johnson.computer
    ipAddress: 10.0.2.14
    installDisk: /dev/nvme0n1
    controlPlane: true
    nodeLabels:
      kubernetes.io/hostname: hv05.clt.johnson.computer
      topology.kubernetes.io/region: us-east-1
      topology.kubernetes.io/zone: us-east-1a
      node.kubernetes.io/instance-type: r430-gen2-r2
    nameservers:
      - 1.0.0.1
      - 1.1.1.1
    networkInterfaces:
      - interface: eth4
        addresses:
          - 10.0.2.14/24
        mtu: 1500
        routes:
          - network: 0.0.0.0/0
            gateway: 10.0.2.1
        vip: *control_node_vip
        # wireguard:
        #   privateKey: 6NtibgkNWGSLp7ud6NgZr9k3kNhlQiaJCVW6vN+j9UY=
        #   listenPort: 51111
        #   peers:
        #     - publicKey: kyiu4YOZqX+7tY4fdiIRNDe2lSEvlun76EWtD/jP1hU=
        #       endpoint: 192.168.1.3:1111
        #       allowedIPs:
        #         - 192.168.1.0/24
        #       persistentKeepaliveInterval: 10s
      # eno1
      - interface: eth0
        dhcp: false
        ignore: true
      # eno2
      - interface: eth1
        dhcp: false
        ignore: true
      # eno3
      - interface: eth2
        dhcp: false
        ignore: true
      # eno4
      - interface: eth3
        dhcp: false
        ignore: true
  # - hostname: kworker1
  #   ipAddress: 192.168.200.13
  #   controlPlane: false
  #   installDisk: /dev/sdb
  #   patches:
  #     - |-
  #       machine:
  #         network:
  #           interfaces:
  #             - addresses:
  #                 - 192.168.200.11/24
  #               interface: eth1
  #               routes:
  #                 - gateway: 192.168.200.1
  #                 - network: 0.0.0.0/0

controlPlane:
  patches:
    - "@./patches/intel-ucode.yaml"
    - "@./patches/kernel-args.yaml"
    - "@./patches/talos-config.yaml"
    - "@./patches/sysctls.yaml"
    - "@./patches/host-entries.yaml"
    - "@./patches/udev-rules.yaml"
    - "@./patches/kube-apiserver-config.yaml"
    - "@./patches/kubelet-config.yaml"

worker:
  patches:
    - "@./patches/intel-ucode.yaml"
    - "@./patches/kernel-args.yaml"
    - "@./patches/talos-config.yaml"
    - "@./patches/sysctls.yaml"
    - "@./patches/host-entries.yaml"
    - "@./patches/udev-rules.yaml"
    - "@./patches/kubelet-config.yaml"
